services:
  react-app:
    image: node:16.17.1
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true